# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C964_final.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!
from collections import OrderedDict

from PyQt5 import QtCore, QtGui, QtWidgets

import data


class Ui_HeartWise(object):
    def setupUi(self, HeartWise):
        HeartWise.setObjectName("HeartWise")
        HeartWise.resize(297, 603)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        HeartWise.setFont(font)
        self.centralwidget = QtWidgets.QWidget(HeartWise)
        self.centralwidget.setObjectName("centralwidget")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(40, 0, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(26)
        font.setUnderline(True)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 70, 271, 531))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.userInfo = QtWidgets.QLabel(self.groupBox)
        self.userInfo.setGeometry(QtCore.QRect(20, 40, 47, 13))
        self.userInfo.setText("")
        self.userInfo.setObjectName("userInfo")
        self.heartDiseaseLabel = QtWidgets.QLabel(self.groupBox)
        self.heartDiseaseLabel.setGeometry(QtCore.QRect(10, 330, 47, 13))
        self.heartDiseaseLabel.setText("")
        self.heartDiseaseLabel.setObjectName("heartDiseaseLabel")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 19, 251, 411))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.ageSpin = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.ageSpin.setProperty("value", 40)
        self.ageSpin.setObjectName("ageSpin")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ageSpin)
        self.sexSpin = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.sexSpin.setMaximum(1)
        self.sexSpin.setObjectName("sexSpin")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sexSpin)
        self.chestSpin = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.chestSpin.setMaximum(3)
        self.chestSpin.setObjectName("chestSpin")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.chestSpin)
        self.bloodSpin = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.bloodSpin.setMaximum(400)
        self.bloodSpin.setProperty("value", 132)
        self.bloodSpin.setObjectName("bloodSpin")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bloodSpin)
        self.cholesterSpin = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.cholesterSpin.setMaximum(1000)
        self.cholesterSpin.setProperty("value", 246)
        self.cholesterSpin.setObjectName("cholesterSpin")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cholesterSpin)
        self.fbsSpin = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.fbsSpin.setMaximum(1000)
        self.fbsSpin.setDisplayIntegerBase(10)
        self.fbsSpin.setObjectName("fbsSpin")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.fbsSpin)
        self.ecgSpin = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.ecgSpin.setMaximum(2)
        self.ecgSpin.setObjectName("ecgSpin")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.ecgSpin)
        self.hrSpin = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.hrSpin.setMaximum(300)
        self.hrSpin.setProperty("value", 150)
        self.hrSpin.setObjectName("hrSpin")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.hrSpin)
        self.anginaSpin = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.anginaSpin.setMaximum(1)
        self.anginaSpin.setObjectName("anginaSpin")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.anginaSpin)
        self.depressionSpin = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.depressionSpin.setMaximum(20.0)
        self.depressionSpin.setSingleStep(0.1)
        self.depressionSpin.setProperty("value", 1.0)
        self.depressionSpin.setObjectName("depressionSpin")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.depressionSpin)
        self.slopeSpin = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.slopeSpin.setMaximum(2)
        self.slopeSpin.setObjectName("slopeSpin")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.slopeSpin)
        self.caSpin = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.caSpin.setMaximum(3)
        self.caSpin.setObjectName("caSpin")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.caSpin)
        self.thalSpin = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.thalSpin.setMaximum(2)
        self.thalSpin.setObjectName("thalSpin")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.thalSpin)


        self.userInfoButton = QtWidgets.QPushButton(self.groupBox)
        self.userInfoButton.setGeometry(QtCore.QRect(130, 440, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        self.userInfoButton.setFont(font)
        self.userInfoButton.setObjectName("userInfoButton")
        self.userInfoButton.clicked.connect(self.userInput)

        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 510, 47, 13))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        HeartWise.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HeartWise)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 297, 20))
        self.menubar.setObjectName("menubar")
        HeartWise.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HeartWise)
        self.statusbar.setObjectName("statusbar")
        HeartWise.setStatusBar(self.statusbar)

        self.retranslateUi(HeartWise)
        QtCore.QMetaObject.connectSlotsByName(HeartWise)

    def retranslateUi(self, HeartWise):
        _translate = QtCore.QCoreApplication.translate
        HeartWise.setWindowTitle(_translate("HeartWise", "MainWindow"))
        self.Title.setText(_translate("HeartWise", "Heart Wise"))
        self.groupBox.setTitle(_translate("HeartWise", "User Information"))
        self.label.setText(_translate("HeartWise", "Age:"))
        self.label_2.setText(_translate("HeartWise", "Sex:"))
        self.label_3.setText(_translate("HeartWise", "Chest Pain:"))
        self.label_4.setText(_translate("HeartWise", "Blood Pressure:"))
        self.label_5.setText(_translate("HeartWise", "Cholesterol:"))
        self.label_6.setText(_translate("HeartWise", "Blood Sugar(>120):"))
        self.label_7.setText(_translate("HeartWise", "ECG Results:"))
        self.label_8.setText(_translate("HeartWise", "Max Heart Rate:"))
        self.label_9.setText(_translate("HeartWise", "Angina:"))
        self.label_11.setText(_translate("HeartWise", "ST Depression:"))
        self.label_12.setText(_translate("HeartWise", "ST Slope:"))
        self.label_13.setText(_translate("HeartWise", "Occluded Vessels:"))
        self.label_14.setText(_translate("HeartWise", "Thal Defect:"))
        self.userInfoButton.setText(_translate("HeartWise", "Submit"))

    def userInput(self):

        global userInfo
        if self.userInfoButton.isChecked:
            userInfo = OrderedDict([('age', self.ageSpin.value()), ('sex', self.sexSpin.value()),
                                    ('cp', self.chestSpin.value()), ('trestbps', self.bloodSpin.value()),
                                    ('chol', self.cholesterSpin.value()), ('fbs', self.fbsSpin.value()),
                                    ('restecg', self.ecgSpin.value()), ('thalach', self.hrSpin.value()),
                                    ('exang', self.anginaSpin.value()), ('oldpeak', self.depressionSpin.value()),
                                    ('slope', self.slopeSpin.value()), ('ca', self.caSpin.value()),
                                    ('thal', self.thalSpin.value())])
        data.trainingModel(userInfo)


    def updateResult(self, predict):
        print("test")


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    HeartWise = QtWidgets.QMainWindow()
    ui = Ui_HeartWise()
    ui.setupUi(HeartWise)
    HeartWise.show()
    sys.exit(app.exec_())
